### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [wizardamigos/skilltree#5]
## `@todo`
* [ ] [`skilltree#1` workshop - chain of fallbacks](https://github.com/wizardamigos/skilltree/issues/1)
* [ ] [`skilltree#2` workshop - how to learn](https://github.com/wizardamigos/skilltree/issues/2)
* [ ] [`skilltree#3` add workshop](https://github.com/wizardamigos/skilltree/issues/3)
* [ ] [`skilltree#4` inspiration](https://github.com/wizardamigos/skilltree/issues/4)

---
